version: '3.1'

services:
  identities_db:
    image: postgres:11-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identities

  identities_db_client:
    image:  dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@labelengine.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    depends_on:
      - identities_db

  oauth:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - identities_db

volumes:
  db_volume:
